# Common configurations applicable to all environments
spring:
  profiles:
    active: dev  # Set the default profile to 'dev'
  main:
    web-application-type: servlet
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'

logging:
  level:
    root: INFO

server:
  port: 80  # This will enforce port 80 across all profiles

---

# Development profile configuration
spring:
  config:
    activate:
      on-profile: dev
  jwt:
    secret-key: json_web_token_secret_key_for_development_environment
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

---

# Another development profile configuration (dev2)
spring:
  config:
    activate:
      on-profile: dev2
  jwt:
    secret-key: json_web_token_secret_key_for_development_environment
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration
  datasource:
    url: jdbc:postgresql://postgresdb:5432/user_service
    username: user1
    password: password1

---

# Production profile configuration
spring:
  config:
    activate:
      on-profile: prod
  jwt:
    secret-key: ${JWT_SECRET}
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true