version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network
      - database-network

  postgresdb:
    image: postgres:14
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/create_postgres_databases.sql:/docker-entrypoint-initdb.d/create_postgres_databases.sql
    networks:
      - database-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - database-network

  users:
    build:
      context: ./apps/backend/services/users
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./apps/backend/services/users:/app
      - /app/libs
    labels: 
      - "traefik.http.routers.users.rule=(Host(`localhost`) && PathPrefix(`/users`))"
      - "traefik.http.middlewares.users-strip-prefix.stripprefix.prefixes=/users"
      - "traefik.http.routers.users.middlewares=users-strip-prefix"
    networks:
      - database-network
      - traefik-network
    depends_on:
      - postgresdb
      - traefik
    environment:
      SPRING_PROFILES_ACTIVE: dev2

  direct-messaging:
    build:
      context: ./apps/backend/services/direct-messaging
      dockerfile: Dockerfile.dev
    ports:
      - "3001:80"
    networks:
      - database-network
      - traefik-network
    labels: 
      - "traefik.http.routers.direct-messaging.rule=(Host(`localhost`) && PathPrefix(`/direct-messaging`))"
    volumes:
      - ./apps/backend/services/direct-messaging:/app
      - /app/dist
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - mongodb
      - traefik
    environment:
      DIRECT_MESSAGING_MONGODB_URL: mongodb://mongodb:27017/direct_messaging

volumes:
  db_data:
  mongo_data:

networks:
  database-network:
    driver: bridge
  traefik-network:
    driver: bridge