namespace: prod

host: api.draftfrat.com

directMessaging: 
  config:
    name: direct-messaging-config-v1
    data:
      DIRECT_MESSAGING_MONGODB_URL: ""

users: 
  name: users-app
  image: 
    name: draftfrat/users
    tag: latest
  config:
    name: users-config-v1
    data:
      SPRING_PROFILES_ACTIVE: dev2
      DATASOURCE_URL: ""
      DATASOURCE_USERNAME: ""
      DATASOURCE_PASSWORD: ""