namespace: default

host: api.draftfrat.com

drafting: 
  name: drafting-app
  image: 
    name: draftfrat/drafting
    tag: latest
  config:
    name: drafting-config-v1
    data:
      POSTGRES_DATABASE_URL: ""
      REDIS_URL: ""

directMessaging: 
  name: direct-messaging-app
  image: 
    name: draftfrat/direct-messaging
    tag: latest
  config:
    name: direct-messaging-config-v1
    data:
      SPRING_PROFILES_ACTIVE: ""

users: 
  name: users-app
  image: 
    name: draftfrat/users
    tag: latest
  config:
    name: users-config-v1
    data:
      SPRING_PROFILES_ACTIVE: dev
      DATASOURCE_URL: ""
      DATASOURCE_USERNAME: ""
      DATASOURCE_PASSWORD: ""

mongodb:
  isEnabled: false

postgresql:
  isEnabled: false