namespace: default

host: api.draftfrat.com

directMessaging: 
  name: direct-messaging-app
  image: 
    name: draftfrat/direct-messaging
    tag: latest
  config:
    name: direct-messaging-config-v1
    data:
      MONGODB_URL: mongodb://mongo:27017/direct-messaging