namespace: dev

host: ""

directMessaging: 
  config:
    name: direct-messaging-config-v1
    data:
      DIRECT_MESSAGING_MONGODB_URL: mongodb://username:password@mongodb.dev.svc.cluster.local:27017/direct_messaging

drafting: 
  config:
    name: drafting-config-v1
    data:
      POSTGRES_DATABASE_URL: postgresql://username:password@postgresql:5432/drafting
      REDIS_URL: redis://redis:6379

users: 
  name: users-app
  image: 
    name: draftfrat/users
    tag: latest
  config:
    name: users-config-v1
    data:
      SPRING_PROFILES_ACTIVE: dev
      DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/users"
      DATASOURCE_USERNAME: "username"
      DATASOURCE_PASSWORD: "password"

mongodb:
  isEnabled: true

postgresql:
  isEnabled: true