namespace: prod

host: api.rosterroyale.com

directMessaging: 
  config:
    name: direct-messaging-config-v1
    data:
      MONGODB_URL: proddb

ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      loadBalancerIP: {{ .Values.loadBalancerIP | default "" }}