apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.drafting.config.name }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DATABASE_URL: {{ .Values.drafting.config.data.POSTGRES_DATABASE_URL }}
  REDIS_URL: {{ .Values.drafting.config.data.REDIS_URL }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.drafting.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.drafting.name }}
    tier: backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.drafting.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.drafting.name }}
      annotations:
        configmap.revision: {{ .Values.drafting.config.data.POSTGRES_DATABASE_URL | quote }}
    spec:
      containers:
        - name: drafting-container
          image: "{{ .Values.drafting.image.name }}:{{ .Values.drafting.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .Values.drafting.config.name }}
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "526Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.drafting.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.drafting.name }}
    tier: backend
spec:
  selector:
    app: {{ .Values.drafting.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP