apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: draftbash-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /direct-messaging(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.directMessaging.name }}
            port:
              number: 80

      - path: /drafting(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.drafting.name }}
            port:
              number: 80

      - path: /users(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.users.name }}
            port:
              number: 80