apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: draftbash-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-http2: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /direct-messages
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.directMessaging.name }}
            port:
              number: 80