{{- if .Values.mongodb.isEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: bitnami/mongodb:latest
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: password
            - name: MONGODB_USERNAME
              value: username
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_DATABASE
              value: direct_messaging
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
{{- end }}