{{- if .Values.postgresql.isEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: bitnami/postgresql:latest
          env:
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.users.config.data.DATASOURCE_PASSWORD }}
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.users.config.data.DATASOURCE_USERNAME }}
            - name: POSTGRESQL_DATABASE
              value: "default"
            - name: POSTGRESQL_POSTGRES_PASSWORD
              value: {{ .Values.users.config.data.DATASOURCE_PASSWORD }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: custom-init-scripts
          configMap:
            name: postgresql-init-scripts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
data:
  create-multiple-databases.sql: |
    CREATE DATABASE users;
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
{{- end }}