version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - postgres-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge