name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/web/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
            
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install gke-cloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Synchronzie frontend
        run: |
          cd apps/frontend/web
          echo "VITE_SERVER_URL=https://draftfrat.com" >> .env
          npm install
          npm run build
          gsutil -m rsync -r -d dist/ gs://draftfrat.com/