name: Deploy Infrastructure

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        run: terraform -chdir=apps/backend/terraform init

      - name: Terraform Apply
        run: terraform -chdir=apps/backend/terraform apply -auto-approve

      - name: Capture LoadBalancer IP
        id: capture_ip
        run: |
          # Capture the IP using terraform output and sanitize it
          LOADBALANCER_IP=$(terraform -chdir=apps/backend/terraform output -raw static_ip | tr -d '\n' | tr -d '"')
          
          # Ensure we have the correct LoadBalancer IP
          echo "Sanitized LoadBalancer IP: $LOADBALANCER_IP"
          
          # Store the result in GITHUB_OUTPUT for use in later steps
          echo "LOADBALANCER_IP=$LOADBALANCER_IP" >> $GITHUB_OUTPUT

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Install/upgrade helm chart
        run: |
          # Access the captured LoadBalancer IP
          echo "Using LoadBalancer IP: ${{ steps.capture_ip.outputs.LOADBALANCER_IP }}"
          
          # Install or upgrade Helm chart using the captured IP
          helm upgrade --install rosterroyale-release-prod apps/backend/kubernetes \
          --set service.loadBalancerIP=${{ steps.capture_ip.outputs.LOADBALANCER_IP }} \
          --namespace prod