name: Deploy Infrastructure

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: rosterroyale-cluster
      ZONE: us-central1-a
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json # Point to the credentials file

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Create GCP Credentials File
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > ${{ github.workspace }}/gcp-credentials.json

      - name: Terraform Init
        run: |
          cd apps/backend/terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd apps/backend/terraform
          export TF_LOG=DEBUG
          terraform plan -out=tfplan -var "cluster_name=${CLUSTER_NAME}" -var "zone=${ZONE}"

      - name: Terraform Apply
        run: |
          cd apps/backend/terraform 
          terraform apply -auto-approve tfplan

  kubernetes:
    needs: terraform
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: rosterroyale-cluster
      ZONE: us-central1-a
      PROJECT_ID: rosterroyale

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install gke-cloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get GKE credentials
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE} --project ${PROJECT_ID}

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    
      - name: Create namespace
        run: |
          cd apps/backend/kubernetes
          kubectl create namespace prod

      - name: Helm Install
        run: |
          cd apps/backend/kubernetes
          helm install rosterroyale-release-prod apps/backend/kubernetes --values values.yaml -f values-prod.yaml -n prod

      - name: Helm Upgrade
        run: |
          cd apps/backend/kubernetes
          helm upgrade rosterroyale-release-prod apps/backend/kubernetes --values values.yaml -f values-prod.yaml -n prod